name: CI

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Install Dependencies
      #   run: |
      #     pip install -r requirements.txt
      - name: Lint
        run: |
          pylint scripts
      - name: Test
        run: |
          pytest
